### PR TITLE
Re-fix vendor CDNs

### PR DESCRIPTION
**Pull request by matthew-shaw**
Removed vendor directory from project. Using Bootstrap and Google CDNs for best availability and pre-caching. Also changed refs to be non-protocol specific, i.e. works on HTTP and HTTPS.

### CODE REVIEW

**Comment by matthew-shaw** [comment]
@AndyPorter Good one for you to take a look at and merge here. This link supports my reasons for doing this for both Bootstrap and JQuery: http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/

**Comment by richardjpope** [comment]
Merging, but we should revert to using local bootstrap, not CDN, at some point int he future.

**Comment by matthew-shaw** [comment]
@memespring How come? Just curious.

**Comment by matthew-shaw** [comment]
@memespring Also, this wasn't actually merged?

**Comment by richardjpope** [comment]
@matthew-shaw you wouldn't really want to trust external js/css on your app. eg whoever is in control of the domain could use css/js to change what the user sees.

**Comment by richardjpope** [comment]
@matthew-shaw sorry, could you reopen?

**Pull request merged**
